CREATE TABLE users
(
    user_id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(15) NOT NULL UNIQUE,
    fname VARCHAR(100) NOT NULL,
    lname VARCHAR(100) NOT NULL,
    salt INT UNGISGNED NOT NULL,
    pwd CHAR(40) NOT NULL
)